{% set name = "mscorefonts" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pushcx/corefonts/archive/master.zip
  sha256: 7d3c7abe6c6f21e1a48fa1cafccb1005dcfcff9ad2f135ae219854ace6be42d0

build:
  number: 2
  skip: True  # [not linux]

requirements:
  build:
    - cabextract
  host:
    - matplotlib

test:
  commands:
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/andalemo.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/ariali.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/cour.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/georgia.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/impact.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/timesi.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/trebucit.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/verdanaz.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/arial.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/ariblk.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/courbd.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/georgiab.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/times.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/trebuc.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/verdana.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/webdings.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/arialbd.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/comic.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/courbi.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/georgiai.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/timesbd.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/trebucbd.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/verdanab.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/arialbi.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/comicbd.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/couri.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/georgiaz.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/timesbi.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/trebucbi.ttf  # [unix]
    - test -f $SP_DIR/matplotlib/mpl-data/fonts/ttf/verdanai.ttf  # [unix]

about:
  home: https://sourceforge.net/projects/mscorefonts
  license: PROPRIETARY
  license_family: PROPRIETARY
  license_file: LICENSE
  summary: 'Microsofts Core fonts for the Web'

  description: |
    In 1996 Microsoft started a font project named Core fonts 
    for the Web. It was a freeware font project including fonts 
    Andale Mono, Arial, Arial Black, Comic Sans MS, Courier New, 
    Georgia, Impact, Times New Roman, Trebuchet MS, Verdana and 
    Webdings.

  doc_url: https://sourceforge.net/projects/mscorefonts/
  dev_url: https://sourceforge.net/projects/mscorefonts/

extra:
  recipe-maintainers:
    - jan-janssen
