travis:
  secure:
    BINSTAR_TOKEN: LVznxh88O4dJk1eEHPI3EVE6PVxstSowEEcrNJyh1vbzc5qgnTzn+Zzs9L4G7R2nlO9OTbjAmn0zASZNm4e4QXRj7vEcNMEinWyXwDRB3mE5RsPK+1ZDotmvZKqM6claGLRo/QcnDkh3tvxQkPNWIGzFS81K40MpySwk1X3NZjMaBiM6CSzILl2LHwVS/E3MT5oigY5JkxrmiXY78DgYB0Zu/IzzCcpCpLyrR5O8VyAOG6nRczo5CKBZ1FIorJPFOXTmdrt+syJ/b40Rz7x0pbpAx66gAGQZJqRGjUQVSHMsoVJX0iFts0nnu/SRTYah8w/EyDJvFKsBdYB8rGJvPAwDuHadks5dmLUPlYInf18TfmfiIDHDPLT+jg/vQB0C4af/2d24UPJszzqOYKUmaTf1qxCuqZXht7H92hJ5JU0cnS/ZIKv1NQW9e3WPoXbLs+OYWUgnm9kvTss7tZMKxwtfgWbq7WmI0MCRLSbXcmkbBuVjdf3+7FL0JHt3jobcTpLMaCWDD1Npf55u1i7f0/75dToQH657bT6LwossmvRkrOR8xwxksVp1y30PdA2AlmoZpeJ2/0cRwnzdfxHpiXRo4nKyEIifVOfBhNsa3P6+bA4j7pgHKl0kIpeKeoR2Y4gQaXjy6HCIb6qsXx24n019qwpuqgH04Vx5MNfoodo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
